- hosts: all
  tasks:
    # Facter facts are not available without first installing
    # both facter *and* the json gem (necessary to support
    # facter's --json option).
    - name: make sure facter is installed
      yum: name={{item}} state=latest
      with_items:
        - rubygem-json
        - facter

- hosts: all
  tasks:
    - name: add compute and storage nodes to /etc/hosts
      lineinfile: dest=/etc/hosts
                   line="{{hostvars[item].ansible_eth0.ipv4.address}} {{hostvars[item].facter_hostname}} {{hostvars[item].facter_hostname}}.localdomain {{item}}"
                   regexp="{{hostvars[item].facter_hostname}}"
                   state=present
      with_items: groups.compute + groups.storage
    - name: add controller and network nodes to /etc/hosts
      lineinfile: dest=/etc/hosts
                   line="{{hostvars[item].ansible_eth0.ipv4.address}} {{hostvars[item].facter_hostname}} {{hostvars[item].facter_hostname}}.localdomain {{item}}"
                   regexp="{{hostvars[item].facter_hostname}}"
                   state=present
      with_items:
        - controller
        - network

