- hosts:
    - controller
    - compute
  gather_facts: false
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - glusterfs-fuse
        - glusterfs-libs
    - mount: fstype=glusterfs name=/mnt/{{item}} src={{hostvars.storage0.storage_ip}}:/{{item}} state=mounted
      with_items:
        - glance
        - nova

- hosts: compute
  tasks:
    - name: configure nova to use gluster
      ini_file: dest=/etc/nova/nova.conf section=DEFAULT
                option={{item.option}} value={{item.value}}
      with_items:
        - {option: "instances_path",      value: "/mnt/nova"}
        - {option: "qemu_allowed_storage_drivers",
            value: "gluster"}
      notify: restart nova

