- hosts: storage
  gather_facts: false
  pre_tasks:
    - file: path=/export state=directory owner=root group=root mode=0755
  roles:
    - role: gluster-server
    - role: gluster-brick
      brick_device: /dev/vdb
      brick_mountpoint: /export/vdb

- hosts: storage
  gather_facts: false
  tasks:
    - file: path=/export/vdb/brick_{{item}} state=directory owner=root group=root mode=0755
      with_items:
        - nova
        - glance
        - cinder

- hosts: storage0
  gather_facts: false
  tasks:
    - command: gluster peer probe "{{hostvars[item].storage_ip}}"
      with_items: groups.storage

- hosts: storage0
  gather_facts: false
  roles:
    - role: gluster-volume
      volume_name: cinder
      volume_bricks: 
        - "{{hostvars.storage0.storage_ip}}:/export/vdb/brick_cinder"
        - "{{hostvars.storage1.storage_ip}}:/export/vdb/brick_cinder"
      volume_options:
        - {name: group, value: virt}
        - {name: storage.owner-uid, value: 165}
        - {name: storage.owner-gid, value: 165}
    - role: gluster-volume
      volume_name: nova
      volume_bricks:
        - "{{hostvars.storage0.storage_ip}}:/export/vdb/brick_nova"
        - "{{hostvars.storage1.storage_ip}}:/export/vdb/brick_nova"
      volume_options:
        - {name: group, value: virt}
        - {name: storage.owner-uid, value: 162}
        - {name: storage.owner-gid, value: 162}
    - role: gluster-volume
      volume_name: glance
      volume_bricks: 
        - "{{hostvars.storage0.storage_ip}}:/export/vdb/brick_glance"
        - "{{hostvars.storage1.storage_ip}}:/export/vdb/brick_glance"
      volume_options:
        - {name: group, value: virt}
        - {name: storage.owner-uid, value: 161}
        - {name: storage.owner-gid, value: 161}

