- hosts: all
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - man
        - vim-enhanced
        - git
        - screen
        - tcpdump

- hosts: compute
  tasks:
    - yum: name={{item}} state=latest
      with_items:
        - sysfsutils
