- hosts: controller
  gather_facts: false
  tasks:
    - file: path=/root/.ssh state=directory owner=root group=root mode=0700
    - file: path=/root/.ssh/id_rsa state=file
      ignore_errors: true
      register: ssh_key
    - name: generate ssh key for root
      command: ssh-keygen -t rsa -b 2048 -N '' -f /root/.ssh/id_rsa
      when: ssh_key|failed
    - name: fetch root ssh public key
      fetch: flat=true src=/root/.ssh/id_rsa.pub dest=controller_id_rsa.pub

- hosts: all
  gather_facts: false
  tasks:
    - authorized_key: user=root key="{{ lookup('file', 'controller_id_rsa.pub') }}"

